### ISSUE TITLE
Cross compilation of libsodium-sys with bindgen doesn't work

### ISSUE THREAD

**Issue by oherrala** [sodiumoxide/sodiumoxide#238]
Compilation of libsodium-sys fails when trying to cross compile (Rust target `armv7-unknown-linux-musleabihf`).

Related bindgen issue https://github.com/rust-lang-nursery/rust-bindgen/issues/1229 which also gave hints to debugging.

Compilation currently fails with:

```
   Compiling libsodium-sys v0.1.0 (file:///build)
     Running `rustc --crate-name build_script_build build.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=7014a955c143834e -C extra-filename=-7014a955c143834e --out-dir /build/target/debug/build/libsodium-sys-7014a955c143834e -C incremental=/build/target/debug/incremental -L dependency=/build/target/debug/deps --extern pkg_config=/build/target/debug/deps/libpkg_config-269e302f3f1b9e79.rlib --extern bindgen=/build/target/debug/deps/libbindgen-f04c2c41173f1b84.rlib -L native=/build/target/debug/build/libloading-8dd136a09db0323c/out`
     Running `/build/target/debug/build/libsodium-sys-7014a955c143834e/build-script-build`
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_INC_DIR
cargo:rerun-if-env-changed=SODIUM_STATIC
cargo:rustc-link-search=native=/opt/libsodium/lib
cargo:rustc-link-lib=static=sodium
warning: unknown platform, assuming -mfloat-abi=soft
warning: unknown platform, assuming -mfloat-abi=soft
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
warning: unknown platform, assuming -mfloat-abi=soft, err: false
warning: unknown platform, assuming -mfloat-abi=soft, err: false
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: failed to run custom build command for `libsodium-sys v0.1.0 (file:///build)`
process didn't exit successfully: `/build/target/debug/build/libsodium-sys-7014a955c143834e/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_INC_DIR
cargo:rerun-if-env-changed=SODIUM_STATIC
cargo:rustc-link-search=native=/opt/libsodium/lib
cargo:rustc-link-lib=static=sodium

--- stderr
warning: unknown platform, assuming -mfloat-abi=soft
warning: unknown platform, assuming -mfloat-abi=soft
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
warning: unknown platform, assuming -mfloat-abi=soft, err: false
warning: unknown platform, assuming -mfloat-abi=soft, err: false
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

and with tweaks to `libsodium-sys/build.rs` I at least got it compiled:

```diff
diff --git a/libsodium-sys/build.rs b/libsodium-sys/build.rs
index 5c0e242c..86a05a24 100644
--- a/libsodium-sys/build.rs
+++ b/libsodium-sys/build.rs
@@ -25,17 +25,21 @@ fn main() {
     let include_dir = match env::var("SODIUM_INC_DIR") {
         Ok(dir) => dir,
         Err(_) => pkg_config::get_variable("libsodium", "includedir").unwrap()
     };
 
+    let target = env::var("TARGET").unwrap();
+
     let bindings = bindgen::Builder::default()
         .header("sodium_wrapper.h")
         .whitelist_function("(sodium|crypto|randombytes)_.*")
         .whitelist_type("(sodium|crypto|randombytes)_.*")
         .whitelist_var("(sodium|crypto|randombytes)_.*")
-        .clang_arg("-isystem")
-        .clang_arg(include_dir)
+        .clang_args(&["-target", &target])
+        .clang_args(&["-I", "/opt/armv7-linux-musleabihf/armv7-linux-musleabihf/include/"])
+        .clang_args(&["-I", &include_dir])
+        .rustfmt_bindings(false)
         .generate()
         .expect("Unable to generate bindings");
 
     let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
     bindings
```

Seems pretty basic except I don't know how to pass the include path `-I /opt/armv7-linux-musleabihf/armv7-linux-musleabihf/include/` into there from environment.

With the patch above it compiles, but some warnings are still left:

```
   Compiling libsodium-sys v0.1.0 (file:///build)
     Running `rustc --crate-name build_script_build build.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=7014a955c143834e -C extra-filename=-7014a955c143834e
 --out-dir /build/target/debug/build/libsodium-sys-7014a955c143834e -C incremental=/build/target/debug/incremental -L dependency=/build/target/debug/deps --extern bindgen=/build/
target/debug/deps/libbindgen-f04c2c41173f1b84.rlib --extern pkg_config=/build/target/debug/deps/libpkg_config-269e302f3f1b9e79.rlib -L native=/build/target/debug/build/libloading
-8dd136a09db0323c/out`
     Running `/build/target/debug/build/libsodium-sys-7014a955c143834e/build-script-build`
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_INC_DIR
cargo:rerun-if-env-changed=SODIUM_STATIC
cargo:rustc-link-search=native=/opt/libsodium/lib
cargo:rustc-link-lib=static=sodium
warning: unknown platform, assuming -mfloat-abi=soft, err: false
warning: unknown platform, assuming -mfloat-abi=soft, err: false
/opt/armv7-linux-musleabihf/armv7-linux-musleabihf/include/endian.h:32:25: warning: '&' within '|' [-Wbitwise-op-parentheses], err: false
/opt/armv7-linux-musleabihf/armv7-linux-musleabihf/include/endian.h:32:41: warning: '&' within '|' [-Wbitwise-op-parentheses], err: false
/opt/armv7-linux-musleabihf/armv7-linux-musleabihf/include/endian.h:37:23: warning: operator '<<' has lower precedence than '+'; '+' will be evaluated first [-Wshift-op-parenthes
es], err: false
     Running `rustc --crate-name libsodium_sys src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=5b380d229f3819fe -C extra-filename=-5b380d229f3819fe --
out-dir /build/target/armv7-unknown-linux-musleabihf/debug/deps --target armv7-unknown-linux-musleabihf -C linker=armv7-linux-musleabihf-gcc -C incremental=/build/target/armv7-un
known-linux-musleabihf/debug/incremental -L dependency=/build/target/armv7-unknown-linux-musleabihf/debug/deps -L dependency=/build/target/debug/deps --extern libc=/build/target/
armv7-unknown-linux-musleabihf/debug/deps/liblibc-023064671197992a.rlib -L native=/opt/libsodium/lib -l static=sodium`
    Finished dev [unoptimized + debuginfo] target(s) in 47.25 secs
```

I used this Dockerfile for cross compilation environment:

```dockerfile
FROM sensorfu/rust-musl-arm:1.26.2-0

RUN apt-get -y update && \
    apt-get -y install \
        clang \
        libclang-dev

ARG LIBSODIUM=libsodium-1.0.16

WORKDIR /work
RUN curl -fo- https://download.libsodium.org/libsodium/releases/${LIBSODIUM}.tar.gz | tar zxf - && \
    cd ${LIBSODIUM} && \
     ./configure --prefix=/opt/libsodium --host=armv7-linux-musleabihf --enable-shared=no && \
     make -j4 && \
     make install

WORKDIR /build
COPY . /build/

ENV HOST_CC clang
ENV SODIUM_LIB_DIR=/opt/libsodium/lib
ENV SODIUM_INC_DIR=/opt/libsodium/include
ENV SODIUM_STATIC=1

RUN cargo build -vv --target=armv7-unknown-linux-musleabihf
```

**Comment by kpp** [comment]
@oherrala Hello! would you please test it again?

```
cd sodiumoxide
git pull
git checkout static_bindings
# unset SODIUM* variables
```

And use this(https://github.com/maidsafe/rust_sodium#cross-compiling-for-arm) guide to crosscompile for armv7-unknown-linux-musleabihf?

**Comment by oherrala** [comment]
@kpp Hi!

I got my cross compilation environment working with sodiumoxide! Here's my `Dockerfile` for everyone else wondering how things should be set up.

```dockerfile
FROM rust:1.30.1

ENV TARGET="armv7-unknown-linux-musleabihf"

ARG TOOLCHAIN_ARM7="armv7-eabihf--musl--stable-2018.02-2"
ARG TC_ARM7_URL="https://toolchains.bootlin.com/downloads/releases/toolchains/armv7-eabihf/tarballs/${TOOLCHAIN_ARM7}.tar.bz2"

RUN rustup target add ${TARGET}
COPY cargo.config "${CARGO_HOME}/config"

WORKDIR /opt
RUN curl -o- ${TC_ARM7_URL} | tar -xjf -

ENV PATH="${PATH}:/opt/${TOOLCHAIN_ARM7}/bin"
ENV CC_armv7_unknown_linux_musleabihf=arm-buildroot-linux-musleabihf-gcc
ENV CXX_armv7_unknown_linux_musleabihf=arm-buildroot-linux-musleabihf-g++
ENV LD_armv7_unknown_linux_musleabihf=arm-buildroot-linux-musleabihf-ld

WORKDIR /work
RUN git clone https://github.com/sodiumoxide/sodiumoxide

WORKDIR /work/sodiumoxide
RUN cargo build --target=${TARGET}
```

and `cargo.config`:

```
[target.armv7-unknown-linux-musleabihf]
linker = "arm-buildroot-linux-musleabihf-gcc"
```

Thanks!
