### ISSUE TITLE
crypto::pwhash::argon2i13::test fail on libsodium 1.0.13-1

### ISSUE THREAD

**Issue by kpp** [sodiumoxide/sodiumoxide#280]
```
failures:

---- crypto::pwhash::argon2i13::test::test_verify_1 stdout ----
thread 'crypto::pwhash::argon2i13::test::test_verify_1' panicked at 'failed to verify password with hash', src/crypto/pwhash/argon2i13.rs:480:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- crypto::pwhash::argon2id13::test::test_derive_07 stdout ----
thread 'crypto::pwhash::argon2id13::test::test_derive_07' panicked at 'assertion failed: result.is_ok()', src/crypto/pwhash/argon2id13.rs:370:9

---- crypto::pwhash::argon2id13::test::test_hash_2 stdout ----
thread 'crypto::pwhash::argon2id13::test::test_hash_2' panicked at 'failed to verify password with hash', src/crypto/pwhash/argon2id13.rs:583:9

---- crypto::pwhash::argon2id13::test::test_serialisation stdout ----
thread 'crypto::pwhash::argon2id13::test::test_serialisation' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libcore/result.rs:1009:5

---- crypto::pwhash::argon2id13::test::test_verify_3 stdout ----
thread 'crypto::pwhash::argon2id13::test::test_verify_3' panicked at 'failed to verify password with hash', src/crypto/pwhash/argon2id13.rs:517:9

---- crypto::pwhash::argon2id13::test::test_verify_6 stdout ----
thread 'crypto::pwhash::argon2id13::test::test_verify_6' panicked at 'failed to verify password with hash', src/crypto/pwhash/argon2id13.rs:553:9


failures:
    crypto::pwhash::argon2i13::test::test_verify_1
    crypto::pwhash::argon2id13::test::test_derive_07
    crypto::pwhash::argon2id13::test::test_hash_2
    crypto::pwhash::argon2id13::test::test_serialisation
    crypto::pwhash::argon2id13::test::test_verify_3
    crypto::pwhash::argon2id13::test::test_verify_6

test result: FAILED. 204 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by kpp** [comment]
Same on libsodium-1.0.14

**Comment by kpp** [comment]
libsodium-1.0.15 and libsodium-1.0.16 passed tests

**Comment by kpp** [comment]
Depends on #231

**Comment by Dylan-DPC** [comment]
@kpp we can add it to the docs above the function

**Comment by kpp** [comment]
Yes that should be enough at the moment. But there is more we can do. See https://github.com/maidsafe/rust_sodium/blob/master/rust_sodium-sys/build.rs#L64

**Comment by Dylan-DPC** [comment]
Yah that's the next step :D
